package com.example.nonutsinmybasket.models.apiclasses

import com.google.gson.annotations.SerializedName

data class Nutriments(
    val carbohydrates: Float,
    val carbohydrates_100g: Float,
    val carbohydrates_unit: String,
    val carbohydrates_value: Float,
    val energy: Float,
    @SerializedName("energy-kj") val energy_kj: Float,
    @SerializedName("energy-kj_100g") val energy_kj_100g: Float,
    @SerializedName("energy-kj_unit") val energy_kj_unit: String,
    @SerializedName("energy-kj_value") val energy_kj_value: Float,
    val energy_100g: Float,
    val energy_unit: String,
    val energy_value: Float,
    val fat: Float,
    val fat_100g: Float,
    val fat_unit: String,
    val fat_value: Float,
    @SerializedName("fruits-vegetables-nuts-estimate-from-ingredients_100g") val fruits_vegetables_nuts_estimate_from_ingredients_100g: Float,
    @SerializedName("nova-group") val nova_group: Float,
    @SerializedName("nova-group_100g") val nova_group_100g: Float,
    @SerializedName("nova-group_serving") val nova_group_serving: Float,
    @SerializedName("nutrition-score-fr") val nutrition_score_fr: Float,
    @SerializedName("nutrition-score-fr_100g") val nutrition_score_fr_100g: Float,
    val proteins: Double,
    val proteins_100g: Double,
    val proteins_unit: String,
    val proteins_value: Double,
    val salt: Double,
    val salt_100g: Double,
    val salt_unit: String,
    val salt_value: Double,
    @SerializedName("saturated-fat") val saturated_fat: Float,
    @SerializedName("saturated-fat_100g") val saturated_fat_100g: Float,
    @SerializedName("saturated-fat_unit") val saturated_fat_unit: String,
    @SerializedName("saturated-fat_value") val saturated_fat_value: Float,
    val sodium: Double,
    val sodium_100g: Double,
    val sodium_unit: String,
    val sodium_value: Double,
    val sugars: Float,
    val sugars_100g: Float,
    val sugars_unit: String,
    val sugars_value: Float
)